-- interactive graphics
interactive_graphics = {}
interactive_graphics.button_up        = {}
interactive_graphics.button_up.img    = love.graphics.newImage('sprites/interactive_graphics/button_up.png')
interactive_graphics.button_up.x      = 740
interactive_graphics.button_up.y      = 1080
interactive_graphics.button_down      = {}
interactive_graphics.button_down.img  = love.graphics.newImage('sprites/interactive_graphics/button_down.png')
interactive_graphics.button_down.x    = 748
interactive_graphics.button_down.y    = 1088